<?php

namespace ContainerFrwYXXC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3unXI05Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3unXI05' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3unXI05'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\ReviewController::delete' => ['privates', '.service_locator.Xl2sCQI', 'get_ServiceLocator_Xl2sCQIService', true],
            'App\\Controller\\ReviewController::edit' => ['privates', '.service_locator.Xl2sCQI', 'get_ServiceLocator_Xl2sCQIService', true],
            'App\\Controller\\ReviewController::index' => ['privates', '.service_locator.Yg8pfWR', 'get_ServiceLocator_Yg8pfWRService', true],
            'App\\Controller\\ReviewController::new' => ['privates', '.service_locator.Yg8pfWR', 'get_ServiceLocator_Yg8pfWRService', true],
            'App\\Controller\\ReviewController::show' => ['privates', '.service_locator.8kA_uio', 'get_ServiceLocator_8kAUioService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.0CRkV7m', 'get_ServiceLocator_0CRkV7mService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.3opkxl5', 'get_ServiceLocator_3opkxl5Service', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.8IESKP1', 'get_ServiceLocator_8IESKP1Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.DG8Afcf', 'get_ServiceLocator_DG8AfcfService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\ReviewController:delete' => ['privates', '.service_locator.Xl2sCQI', 'get_ServiceLocator_Xl2sCQIService', true],
            'App\\Controller\\ReviewController:edit' => ['privates', '.service_locator.Xl2sCQI', 'get_ServiceLocator_Xl2sCQIService', true],
            'App\\Controller\\ReviewController:index' => ['privates', '.service_locator.Yg8pfWR', 'get_ServiceLocator_Yg8pfWRService', true],
            'App\\Controller\\ReviewController:new' => ['privates', '.service_locator.Yg8pfWR', 'get_ServiceLocator_Yg8pfWRService', true],
            'App\\Controller\\ReviewController:show' => ['privates', '.service_locator.8kA_uio', 'get_ServiceLocator_8kAUioService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReviewController::delete' => '?',
            'App\\Controller\\ReviewController::edit' => '?',
            'App\\Controller\\ReviewController::index' => '?',
            'App\\Controller\\ReviewController::new' => '?',
            'App\\Controller\\ReviewController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReviewController:delete' => '?',
            'App\\Controller\\ReviewController:edit' => '?',
            'App\\Controller\\ReviewController:index' => '?',
            'App\\Controller\\ReviewController:new' => '?',
            'App\\Controller\\ReviewController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
